baseurl = "/"
languageCode = "pl-pl"
languageLang = "pl"
title = "Biuro ochrony „Centurion”"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
[[menu.main]]
    name = "O nas"
    weight = 1
    identifier = "onas"
    url = "/"
[params]
  description = "Biuro Centurion to firma z wieloletnim stażem, działająca na podstawie koncesji nr L-0073/15 wydanej przez Ministra Spraw Wewnętrznych. W sektorze bezpieczeństwa działamy zarówno na rzecz klientów indywidualnych, jak i dla zorganizowanych podmiotów zewnętrznych."